"""empty message

Revision ID: 00fe8b806573
Revises: 3e297246405f
Create Date: 2019-09-09 15:03:09.266044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00fe8b806573'
down_revision = '3e297246405f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('message', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'message')
    # ### end Alembic commands ###
