"""empty message

Revision ID: 0bc9e5beb9dd
Revises: 0ffba918cfaf
Create Date: 2019-08-28 10:47:17.742360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bc9e5beb9dd'
down_revision = '0ffba918cfaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specialrest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('special_rest', sa.String(length=512), nullable=True),
    sa.Column('type', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specialrest')
    # ### end Alembic commands ###
