"""empty message

Revision ID: 32a5f3712f50
Revises: 00fe8b806573
Create Date: 2019-09-09 15:15:20.529779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32a5f3712f50'
down_revision = '00fe8b806573'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('status', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'status')
    # ### end Alembic commands ###
