"""empty message

Revision ID: 3409ef865171
Revises: 662819aaef6f
Create Date: 2019-08-28 12:43:02.439715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3409ef865171'
down_revision = '662819aaef6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('makeuptime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('make_up_time', sa.DateTime(), nullable=True),
    sa.Column('expire', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('specialrest', sa.Column('expire', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('specialrest', 'expire')
    op.drop_table('makeuptime')
    # ### end Alembic commands ###
