"""empty message

Revision ID: 662819aaef6f
Revises: afa6e182c9b7
Create Date: 2019-08-28 11:52:21.255523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '662819aaef6f'
down_revision = 'afa6e182c9b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specialrest', sa.Column('rest_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('specialrest', 'rest_time')
    # ### end Alembic commands ###
