"""empty message

Revision ID: 7dd36eed134c
Revises: cd49e37f9d5d
Create Date: 2019-09-10 17:51:29.386862

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7dd36eed134c'
down_revision = 'cd49e37f9d5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'timezone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('timezone', mysql.VARCHAR(length=8), nullable=True))
    # ### end Alembic commands ###
