"""empty message

Revision ID: 9164df9b23b7
Revises: 7dd36eed134c
Create Date: 2019-09-14 17:39:02.237561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9164df9b23b7'
down_revision = '7dd36eed134c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=32), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('job', sa.String(length=128), nullable=True),
    sa.Column('family', sa.String(length=128), nullable=True),
    sa.Column('personality', sa.String(length=128), nullable=True),
    sa.Column('hobby', sa.String(length=128), nullable=True),
    sa.Column('taboo', sa.String(length=128), nullable=True),
    sa.Column('reason', sa.String(length=128), nullable=True),
    sa.Column('goal', sa.String(length=128), nullable=True),
    sa.Column('level', sa.String(length=128), nullable=True),
    sa.Column('ability', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.String(length=128), nullable=True),
    sa.Column('homework', sa.String(length=128), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('teacher_phone', sa.String(length=128), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_profiles')
    # ### end Alembic commands ###
