"""empty message

Revision ID: afa6e182c9b7
Revises: 0bc9e5beb9dd
Create Date: 2019-08-28 11:51:15.217447

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'afa6e182c9b7'
down_revision = '0bc9e5beb9dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('specialrest', 'special_rest')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specialrest', sa.Column('special_rest', mysql.VARCHAR(length=512), nullable=True))
    # ### end Alembic commands ###
