"""empty message

Revision ID: cd49e37f9d5d
Revises: 32a5f3712f50
Create Date: 2019-09-09 15:53:55.885263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd49e37f9d5d'
down_revision = '32a5f3712f50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('lesson_type', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'lesson_type')
    # ### end Alembic commands ###
